#!/bin/zsh
#
# This lets you quickly jump into a dev directory.
#
# Type:
#
#   dev <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_d`.

cd "$DEV/$1"
