cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'ansible'
brew 'coreutils'
brew 'hub'
brew 'imagemagick'
brew 'jq'
brew 'libgit2'
brew 'nvm'
brew 'openssl'
brew 'readline'
brew 'wget'
brew 'yarn'
brew 'zsh-syntax-highlighting'

cask 'atom'
cask 'docker'
cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
