#!/bin/bash
#
# runs all update.sh files

set -e

DOTFILES="$HOME/.dotfiles"
source "$DOTFILES"/features/utils.sh
export -f info # export to be used in the find/exec subshell
OS_SUFFIX=$(os_suffix)

pull_dotfiles () {
  local BRANCH
  BRANCH=$(git -C "$DOTFILES" rev-parse --abbrev-ref HEAD)

  if [[ ! $BRANCH = "main" ]]; then
    info "Not on main branch, skipping pull_dotfiles"
  elif [[ -n "$(git -C "$DOTFILES" status --porcelain)" ]]; then
    info "Status not clean, skipping pull_dotfiles"
  else
    info "Pulling dotfiles"
    git -C "$DOTFILES" pull --rebase
  fi
}

pull_extensions () {
  for FOLDER in "$DOTFILES"/extensions/*; do
    info "Pulling extension $FOLDER"
    git -C "$FOLDER" pull --rebase
  done
}

exec_updates () {
  find \
    -H "$DOTFILES/features" "$DOTFILES/extensions" \
    -maxdepth 4 \
    -type f \
    \( -name "update.sh" -o -name "update.sh.$OS_SUFFIX" \) \
    -not -path '*.git*' \
    -exec bash -c 'FILE="$0"; info "$FILE"; "$FILE"' {} ';'
}


pull_dotfiles
pull_extensions
exec_updates

success 'update finished'
