#!/bin/sh
#
# Run all dotfiles installers.

# (rafaeleyng) commented this from @holman's because nvm fails with "set -e"
# set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
